services:
  openldap:
    image: "osixia/openldap:latest"
    env_file: ".env"
    hostname: ldap_host
    environment:
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    volumes:
      - ./01-crate_users_groups.ldif:/root/01-crate_users_groups.ldif
      - ./02-base_users.ldif:/root/02-base_users.ldif
      - ./03-admin_group.ldif:/root/03-admin_group.ldif
    ports:
      - "389:389"
      - "636:636"
    networks:
      - local

  phpldapadmin:
    image: "osixia/phpldapadmin:latest"
    env_file: ".env"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap_host
    ports:
      - "8443:443"
    networks:
      - local


networks:
  local:
    external: true

