services:
  redmine:
    image: redmine
    env_file: ".env.mysql"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - local
  mysql:
    image: mysql:8.0
    env_file: ".env.mysql"
    #ports:
      #- '127.0.0.1:3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - local

volumes:
  db:

networks:
  local:
    external: true
